name: Play the game
on:
  issues:
    types: [opened]
jobs:
  playGame:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: computer appropriate responce
        id: computerResponce
        continue-on-error: true
        run: |
          set +e
          LINE=$(echo "$EVENT_ID % $(cat words.txt | wc -l) + 1" | bc)
          echo $LINE
          TARGET=$(head -n $LINE words.txt | tail -n -1)
          GUESS=$(echo $TITLE | cut -c 1-5)
          chmod u+x wordle.py
          ./wordle.py "$TARGET""$GUESS" > output.txt
          echo "result_code=$?" >> "$GITHUB_STEP_SUMMERY"
          cat output.txt >> "$GITHUB_STEP_SUMMERY"
        env:
          EVENT_ID: ${{ github.event.issue.id }}
          TITLE: ${{ github.event.issue.title }}
      - name: Add comment
        run: gh issue comment "$NUMBER" --body "$BODY"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
          BODY: >
            This issue is available for anyone to work on.
            **Make sure to reference this issue in your pull request.**
            :sparkles: Thank you for your contribution! :sparkles:
            ${{ steps.computerResponse.outputs.result_code }}
