name: Play the game
on:
  issues:
    types: [opened]
jobs:
    playGame:
      runs-on: unbuntu-latest
      steps: 
        - name: checkout repo
          uses: actions/checkout@v4
        - name: see event id
          run: |
          echo $EVENT_ID
          echo "$EVENT_ID % $(cat words.txt |wc -l)" | bc
          env:
            EVENT_ID: ${{ github.event.issue.id}}
    
